[project]
name = ""
dynamic = ["version"]
description = ""
authors = [
    {name = "Sebastián Altamirano"},
]
dependencies = [
    "jsonschema>=4.21.1",
]
requires-python = ">=3.8"
license = {text = "MIT"}

[tool.black]
line-length = 100

[tool.isort]
line_length = 100
profile = "black"

[tool.mypy]
check_untyped_defs = true
disallow_any_unimported = true
disallow_untyped_defs = true
no_implicit_optional = true
show_error_codes = true
warn_return_any = true
warn_unused_ignores = true

[tool.pylint.basic]
argument-naming-style = "camelCase"
attr-naming-style = "camelCase"
class-attribute-naming-style = "camelCase"
class-const-naming-style = "UPPER_CASE"
class-naming-style = "PascalCase"
const-naming-style = "UPPER_CASE"
function-naming-style = "camelCase"
method-naming-style = "camelCase"
module-naming-style = "snake_case"
variable-naming-style = "camelCase"

[tool.pdm.dev-dependencies]
format = [
    "black>=23.12.1",
    "isort>=5.13.0",
]
lint = [
    "mypy>=1.8.0",
    "pylint>=3.0.3",
]
typing = [
    "types-jsonschema>=4.21.0.20240118",
    "typing-extensions>=4.9.0",
]

[tool.pdm.scripts]
format = {composite = ["black dotfiles", "isort dotfiles"]}
lint = {composite = ["mypy dotfiles", "pylint dotfiles"]}
test = "python -m unittest discover dotfiles -v -p '*_test.py'"
# These shortcuts may seem useless, but they are necessary to be able to run the tools with
# lint-staged and have them use the configuration specified in `pyproject.toml`.
black = "black"
isort = "isort"
pylint = "pylint"
unittest = "python -m unittest"

[tool.pdm.version]
source = "file"
path = "dotfiles/__init__.py"

[tool.pylint.format]
max-line-length = 100
